export const pastEvents = [
  {
    id: 1,
    name: '',
    date: new Date(2017, 1, 4),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 2,
    name: '',
    date: new Date(2017, 1, 1),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 3,
    name: '',
    date: new Date(2017, 0, 31),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 4,
    name: '',
    date: new Date(2017, 0, 25),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 5,
    name: '',
    date: new Date(2017, 0, 21),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 6,
    name: '',
    date: new Date(2017, 0, 18),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 7,
    name: '',
    date: new Date(2017, 0, 14),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 8,
    name: '',
    date: new Date(2017, 0, 10),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 9,
    name: '',
    date: new Date(2017, 0, 8),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 10,
    name: '',
    date: new Date(2017, 0, 5),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 11,
    name: '',
    date: new Date(2016, 11, 30),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 12,
    name: '',
    date: new Date(2016, 11, 24),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 13,
    name: '',
    date: new Date(2016, 11, 20),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 14,
    name: '',
    date: new Date(2016, 11, 14),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 15,
    name: '',
    date: new Date(2016, 1, 4),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 16,
    name: '',
    date: new Date(2016, 11, 1),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 17,
    name: '',
    date: new Date(2016, 10, 29),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 18,
    name: '',
    date: new Date(2016, 10, 24),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 19,
    name: '',
    date: new Date(2016, 10, 20),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
  {
    id: 20,
    name: '',
    date: new Date(2016, 10, 14),
    city: 'Birmingham',
    country: 'UK',
    place: 'Resorts World Arena',
  },
]

export const upcomingEvents = [];